### ISSUE TITLE
Candidate window not showing up unless ibus-daemon is restarted

### ISSUE THREAD

**Issue by jonathan-alvaro** [chewing/ibus-chewing#199] opened 2024-04-14 13:52 UTC
Desktop environment: Budgie
OS: EndeavourOS

ibus-chewing version: 2.0.0-1 (According to Pacman)

Issue:
When using the zhuyin input method, the candidate window does not appear, making it hard to choose the exact character that I want to type in. But, when I restart the ibus-daemon with the command `ibus-daemon -r`, the problem resolves itself and the zhuyin input candidate window works properly.

**Comment by kanru** [comment] 2024-04-14 22:43
Hi @jonathan-alvaro 

Does the problem appear again after you restart ibus-daemon? Does it appear initially after boot?

**Comment by jonathan-alvaro** [comment] 2024-04-15 01:10
The problem only shows up immediately after boot. When I restart the daemon, the issue disappears.

**Comment by kanru** [comment] 2024-04-15 11:27
@jonathan-alvaro have you also reported this to Arch?

I'll try to install EndeavourOS to test.

cc @yan12125 who maintains the Arch package.

**Comment by jonathan-alvaro** [comment] 2024-04-15 12:09
Not yet.

**Comment by kanru** [comment] 2024-04-15 12:11
I can reproduce in EndeavourOS with the Budgie desktop.

It looks like a Budgie issue that was already reported to ibus in 2018

https://github.com/ibus/ibus/issues/2038

It would be better to file a bug report to Budgie to get it fixed.

https://github.com/BuddiesOfBudgie/budgie-desktop/blob/main/src/wm/ibus.vala#L76

**Comment by yan12125** [comment] 2024-04-15 13:55
yeah, that seems a Budgie issue

**Comment by kanru** [comment] 2024-04-15 23:19
I reported this to Budgie. Closing this issue as this can't be fixed by ibbus-chewing.

**Closed as not planned by kanru** 2024-04-15 23:19 UTC
